In [1]:
import pandas as pd
# read in raw data
AVG_TIME20 = pd.read_csv("C:/Users/Administrator/PycharmProjects/Traffic/Data/training_20min_avg_travel_time-Copy1.csv")
AVG_TIME20['START_TIME'] = AVG_TIME20['time_window'].apply(lambda x :(x.split(','))[0][1:])
AVG_TIME20['TIME'] = pd.DatetimeIndex(AVG_TIME20.START_TIME).time
AVG_TIME20['DATE'] = pd.DatetimeIndex(AVG_TIME20.START_TIME).date
AVG_TIME20['HOUR'] = pd.DatetimeIndex(AVG_TIME20.START_TIME).hour
AVG_TIME20['DAY'] = pd.DatetimeIndex(AVG_TIME20.DATE).dayofweek
AVG_TIME20.drop(['time_window','START_TIME'],axis=1,inplace=True)

In [2]:
AVG_TIME20

,intersection_id,tollgate_id,avg_travel_time,TIME,DATE,HOUR,DAY
0,B,3,70.85,00:00:00,2016-07-19,0,1
1,B,3,148.79,00:20:00,2016-07-19,0,1
2,B,3,93.72,01:40:00,2016-07-19,1,1
3,B,3,67.81,02:00:00,2016-07-19,2,1
4,B,3,167.55,02:40:00,2016-07-19,2,1
5,B,3,98.49,03:40:00,2016-07-19,3,1
6,B,3,96.67,04:00:00,2016-07-19,4,1
7,B,3,53.15,04:20:00,2016-07-19,4,1
8,B,3,55.25,04:40:00,2016-07-19,4,1
9,B,3,209.66,05:00:00,2016-07-19,5,1
10,B,3,145.94,06:00:00,2016-07-19,6,1
11,B,3,127.35,06:20:00,2016-07-19,6,1
12,B,3,97.20,06:40:00,2016-07-19,6,1
13,B,3,118.43,07:00:00,2016-07-19,7,1
14,B,3,82.63,07:20:00,2016-07-19,7,1
15,B,3,110.50,07:40:00,2016-07-19,7,1
16,B,3,125.76,08:00:00,2016-07-19,8,1
17,B,3,141.33,08:20:00,2016-07-19,8,1
18,B,3,176.08,08:40:00,2016-07-19,8,1
19,B,3,165.29,09:00:00,2016-07-19,9,1
20,B,3,127.38,09:20:00,2016-07-19,9,1
21,B,3,117.83,09:40:00,2016-07-19,9,1
22,B,3,98.92,10:00:00,2016-07-19,10,1
23,B,3,113.00,10:20:00,2016-07-19,10,1
24,B,3,98.15,10:40:00,2016-07-19,10,1
25,B,3,95.98,11:00:00,2016-07-19,11,1
26,B,3,84.36,11:20:00,2016-07-19,11,1
27,B,3,96.54,11:40:00,2016-07-19,11,1
28,B,3,144.87,12:00:00,2016-07-19,12,1
29,B,3,136.36,12:20:00,2016-07-19,12,1
...,...,...,...,...,...,...,...
25114,C,1,142.21,10:00:00,2016-10-17,10,0
25115,C,1,166.92,10:20:00,2016-10-17,10,0
25116,C,1,180.04,10:40:00,2016-10-17,10,0
25117,C,1,166.94,11:00:00,2016-10-17,11,0
25118,C,1,153.59,11:20:00,2016-10-17,11,0
25119,C,1,172.90,11:40:00,2016-10-17,11,0
25120,C,1,167.98,12:00:00,2016-10-17,12,0
25121,C,1,203.06,12:20:00,2016-10-17,12,0
25122,C,1,217.37,12:40:00,2016-10-17,12,0
25123,C,1,165.00,13:00:00,2016-10-17,13,0
25124,C,1,218.76,13:20:00,2016-10-17,13,0
25125,C,1,165.84,13:40:00,2016-10-17,13,0
25126,C,1,191.14,14:00:00,2016-10-17,14,0
25127,C,1,187.10,14:20:00,2016-10-17,14,0
25128,C,1,175.01,14:40:00,2016-10-17,14,0
25129,C,1,143.98,15:00:00,2016-10-17,15,0
25130,C,1,134.58,15:20:00,2016-10-17,15,0
25131,C,1,483.07,15:40:00,2016-10-17,15,0
25132,C,1,180.28,16:00:00,2016-10-17,16,0
25133,C,1,150.44,16:20:00,2016-10-17,16,0
25134,C,1,170.89,16:40:00,2016-10-17,16,0
25135,C,1,159.01,17:00:00,2016-10-17,17,0
25136,C,1,170.13,17:20:00,2016-10-17,17,0
25137,C,1,267.11,18:00:00,2016-10-17,18,0
25138,C,1,188.23,19:40:00,2016-10-17,19,0
25139,C,1,171.97,20:40:00,2016-10-17,20,0
25140,C,1,121.61,21:20:00,2016-10-17,21,0
25141,C,1,115.16,22:20:00,2016-10-17,22,0
25142,C,1,194.33,23:00:00,2016-10-17,23,0
25143,C,1,159.78,23:20:00,2016-10-17,23,0